(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/page-component/app-swiper/swiper"],{"047e":function(e,t,a){"use strict";var i=function(){var e=this,t=e.$createElement;e._self._c},n=[];a.d(t,"a",function(){return i}),a.d(t,"b",function(){return n})},"4ec4":function(e,t,a){"use strict";var i=a("9a20"),n=a.n(i);n.a},8486:function(e,t,a){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var i=n(a("7ab7"));function n(e){return e&&e.__esModule?e:{default:e}}var r={name:"bw-swiper",props:{mode:{type:String,default:"scaleToFill"},swiperHeight:{type:Number,default:350},fullScreen:{type:Boolean,default:!1},swiperList:{type:Array,default:function(){return[]}},swiperType:{type:Boolean,default:!1},videoAutoplay:{type:Boolean,default:!1},videoKey:{type:String,default:"src"},imageKey:{type:String,default:"img"},skipHiddenItemLayout:{type:Boolean,default:!1},displayMultipleItems:{type:Number,default:1},nextMargin:{type:String,default:"0px"},previousMargin:{type:String,default:"0px"},vertical:{type:Boolean,default:!1},circular:{type:Boolean,default:!0},duration:{type:Number,default:400},interval:{type:Number,default:2500},current:{type:Number,default:0},autoplay:{type:Boolean,default:!0},indicatorColor:{type:String,default:"#CCCCCC"},indicatorActiveColor:{type:String,default:"#ffffff"},indicatorDots:{type:Boolean,default:!0}},data:function(){return{flag:!0,cardCur:0}},methods:{play:function(){this.flag=!1},pause:function(){this.flag=!0},clickItem:function(e){console.log(e),this.swiperList.length>0&&((0,i.default)({open_type:this.swiperList[e].open_type,params:this.swiperList[e].params,page_url:this.swiperList[e].page_url}),this.$emit("clickItem",this.swiperList[e]))},change:function(e){this.$emit("change",e)},animationfinish:function(e){this.cardCur=e.detail.current,this.$emit("animationfinish",e)}}};t.default=r},"9a20":function(e,t,a){},b6b4:function(e,t,a){"use strict";a.r(t);var i=a("047e"),n=a("fbbc");for(var r in n)"default"!==r&&function(e){a.d(t,e,function(){return n[e]})}(r);a("4ec4");var u=a("2877"),l=Object(u["a"])(n["default"],i["a"],i["b"],!1,null,null,null);t["default"]=l.exports},fbbc:function(e,t,a){"use strict";a.r(t);var i=a("8486"),n=a.n(i);for(var r in i)"default"!==r&&function(e){a.d(t,e,function(){return i[e]})}(r);t["default"]=n.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/page-component/app-swiper/swiper-create-component',
    {
        'components/page-component/app-swiper/swiper-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("b6b4"))
        })
    },
    [['components/page-component/app-swiper/swiper-create-component']]
]);                
