(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/page-component/app-live/app-live"],{"0022":function(e,t,n){"use strict";var o=n("98be"),a=n.n(o);a.a},"207f":function(e,t,n){"use strict";(function(e){Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var n={name:"app-live",components:{},props:{value:{type:Object,default:function(){return{background:"#f7f7f7",live_list:[],is_show_goods:!0,number:5,style_type:1}}}},data:function(){return{}},computed:{newValue:function(){var e=this,t=[{background:e.value.background,is_show_goods:e.value.is_show_goods,number:e.value.number,style_type:e.value.style_type,live_list:[]},{background:e.value.background,is_show_goods:e.value.is_show_goods,number:e.value.number,style_type:e.value.style_type,live_list:[]}],n=0,o=0;return e.value.live_list.forEach(function(e,a){var u=e.goods.length>0;0==n||n<=o?(n=u?n+2:n+1,t[0].live_list.push(e)):(o=u?o+2:o+1,t[1].live_list.push(e))}),t}},mounted:function(){console.log(this.newValue)},methods:{liveClick:function(t){101===t.live_status||102===t.live_status?e.navigateTo({url:"plugin-private://wx2b03c6e691cd7370/pages/live-player-plugin?room_id=".concat(t.roomid)}):103===t.live_status&&(e.setStorage({key:"live_playback",data:{room_info:t}}),e.navigateTo({url:"/pages/live/playback?room_id=".concat(t.roomid)}))}}};t.default=n}).call(this,n("543d")["default"])},"97a9":function(e,t,n){"use strict";n.r(t);var o=n("207f"),a=n.n(o);for(var u in o)"default"!==u&&function(e){n.d(t,e,function(){return o[e]})}(u);t["default"]=a.a},"98be":function(e,t,n){},bb25:function(e,t,n){"use strict";n.r(t);var o=n("cc23"),a=n("97a9");for(var u in a)"default"!==u&&function(e){n.d(t,e,function(){return a[e]})}(u);n("0022");var l=n("2877"),i=Object(l["a"])(a["default"],o["a"],o["b"],!1,null,"1d3dc920",null);t["default"]=i.exports},cc23:function(e,t,n){"use strict";var o=function(){var e=this,t=e.$createElement;e._self._c},a=[];n.d(t,"a",function(){return o}),n.d(t,"b",function(){return a})}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/page-component/app-live/app-live-create-component',
    {
        'components/page-component/app-live/app-live-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("bb25"))
        })
    },
    [['components/page-component/app-live/app-live-create-component']]
]);                
