(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["plugins/bargain/common-buttom"],{"22e0":function(n,t,e){"use strict";(function(n){Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var o=e("2f62");function r(n,t){var e=Object.keys(n);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(n);t&&(o=o.filter(function(t){return Object.getOwnPropertyDescriptor(n,t).enumerable})),e.push.apply(e,o)}return e}function i(n){for(var t=1;t<arguments.length;t++){var e=null!=arguments[t]?arguments[t]:{};t%2?r(e,!0).forEach(function(t){a(n,t,e[t])}):Object.getOwnPropertyDescriptors?Object.defineProperties(n,Object.getOwnPropertyDescriptors(e)):r(e).forEach(function(t){Object.defineProperty(n,t,Object.getOwnPropertyDescriptor(e,t))})}return n}function a(n,t,e){return t in n?Object.defineProperty(n,t,{value:e,enumerable:!0,configurable:!0,writable:!0}):n[t]=e,n}var u=function(){return e.e("components/page-component/app-iphonex-bottom/app-iphonex-bottom").then(e.bind(null,"bc3b"))},c=function(){return Promise.all([e.e("common/vendor"),e.e("components/basic-component/app-iphone-x/app-iphone-x")]).then(e.bind(null,"7598"))},p=function(){return Promise.all([e.e("common/vendor"),e.e("components/basic-component/app-empty-bottom/app-empty-bottom")]).then(e.bind(null,"0c06"))},f={name:"common-buttom",components:{appIphonexBottom:u,appEmptyBottom:p,appIphoneX:c},computed:i({},(0,o.mapState)("gConfig",{iphone:function(n){return n.iphone},iphoneHeight:function(n){return n.iphoneHeight}})),props:{status:{type:String,default:"index"}},data:function(){return{}},methods:{nav1:function(){n.redirectTo({url:"/plugins/bargain/index/index"})},nav2:function(){n.redirectTo({url:"/plugins/bargain/order-list/order-list"})}}};t.default=f}).call(this,e("543d")["default"])},"2faf":function(n,t,e){"use strict";e.r(t);var o=e("3dd2"),r=e("91a1");for(var i in r)"default"!==i&&function(n){e.d(t,n,function(){return r[n]})}(i);e("35bb");var a=e("2877"),u=Object(a["a"])(r["default"],o["a"],o["b"],!1,null,"272da23d",null);t["default"]=u.exports},"35bb":function(n,t,e){"use strict";var o=e("3ba3"),r=e.n(o);r.a},"3ba3":function(n,t,e){},"3dd2":function(n,t,e){"use strict";var o=function(){var n=this,t=n.$createElement,e=(n._self._c,Number(96));n.$mp.data=Object.assign({},{$root:{m0:e}})},r=[];e.d(t,"a",function(){return o}),e.d(t,"b",function(){return r})},"91a1":function(n,t,e){"use strict";e.r(t);var o=e("22e0"),r=e.n(o);for(var i in o)"default"!==i&&function(n){e.d(t,n,function(){return o[n]})}(i);t["default"]=r.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'plugins/bargain/common-buttom-create-component',
    {
        'plugins/bargain/common-buttom-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("2faf"))
        })
    },
    [['plugins/bargain/common-buttom-create-component']]
]);                
