(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/page-component/app-shop/app-shop"],{"0367":function(t,e,n){},"400c":function(t,e,n){"use strict";n.r(e);var u=n("4708"),o=n("dad3");for(var a in o)"default"!==a&&function(t){n.d(e,t,function(){return o[t]})}(a);n("e76a");var r=n("2877"),i=Object(r["a"])(o["default"],u["a"],u["b"],!1,null,"cbd2ee12",null);e["default"]=i.exports},4708:function(t,e,n){"use strict";var u=function(){var t=this,e=t.$createElement;t._self._c},o=[];n.d(e,"a",function(){return u}),n.d(e,"b",function(){return o})},"9abd":function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var u={name:"app-shop",props:{list:{type:Array,default:function(){return[]}},navPicUrl:{type:String,default:function(){return""}},scorePicUrl:{type:String,default:function(){return""}},showName:{type:Boolean,default:function(){return!0}},showScore:{type:Boolean,default:function(){return!0}},showTel:{type:Boolean,default:function(){return!0}},scrollTop:{type:Number,default:function(){return 0}},value:{type:Boolean,default:function(){return!0}}},data:function(){return{height:0,request:!0}},created:function(){var t=this;wx.getSystemInfo({success:function(e){t.height=e.windowHeight}})},methods:{autoEnd:function(){var t=this;this.$lazyLoadingData("app-shop").then(function(e){e[0].height+e[0].top<t.height&&(t.request=!1,t.$emit("input",t.request))})}},watch:{scrollTop:{handler:function(t,e){t>e&&this.request&&this.autoEnd()}}}};e.default=u},dad3:function(t,e,n){"use strict";n.r(e);var u=n("9abd"),o=n.n(u);for(var a in u)"default"!==a&&function(t){n.d(e,t,function(){return u[t]})}(a);e["default"]=o.a},e76a:function(t,e,n){"use strict";var u=n("0367"),o=n.n(u);o.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/page-component/app-shop/app-shop-create-component',
    {
        'components/page-component/app-shop/app-shop-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("400c"))
        })
    },
    [['components/page-component/app-shop/app-shop-create-component']]
]);                
